import { forwardRef } from 'react';

const InvoiceTemplate = forwardRef(({ invoice, user }, ref) => {
  const getStatusColor = (status) => {
    switch (status) {
      case 'Paid':    return '#16a34a';
      case 'Sent':    return '#2563eb';
      case 'Overdue': return '#dc2626';
      default:        return '#6b7280';
    }
  };

  return (
    <div ref={ref} style={styles.page}>

      {/* Header */}
      <div style={styles.header}>
        <div>
          <h1 style={styles.companyName}>
            {user?.company || user?.name || 'SmartBill'}
          </h1>
          <p style={styles.companyEmail}>{user?.email}</p>
        </div>
        <div style={styles.invoiceInfo}>
          <h2 style={styles.invoiceTitle}>INVOICE</h2>
          <p style={styles.invoiceNo}>{invoice.invoiceNo}</p>
          <span style={{
            ...styles.statusBadge,
            color: getStatusColor(invoice.status),
            borderColor: getStatusColor(invoice.status),
          }}>
            {invoice.status}
          </span>
        </div>
      </div>

      <hr style={styles.divider} />

      {/* Client and Date Info */}
      <div style={styles.metaRow}>
        <div>
          <p style={styles.metaLabel}>Billed To</p>
          <p style={styles.metaValue}>{invoice.clientName}</p>
          <p style={styles.metaSubValue}>{invoice.clientEmail}</p>
        </div>
        <div style={{ textAlign: 'right' }}>
          <p style={styles.metaLabel}>Invoice Date</p>
          <p style={styles.metaValue}>
            {new Date(invoice.createdAt).toLocaleDateString('en-US', {
              year: 'numeric', month: 'long', day: 'numeric'
            })}
          </p>
          <p style={styles.metaLabel}>Due Date</p>
          <p style={styles.metaValue}>
            {new Date(invoice.dueDate).toLocaleDateString('en-US', {
              year: 'numeric', month: 'long', day: 'numeric'
            })}
          </p>
        </div>
      </div>

      {/* Line Items Table */}
      <table style={styles.table}>
        <thead>
          <tr style={styles.tableHead}>
            <th style={{ ...styles.th, textAlign: 'left', flex: 3 }}>
              Description
            </th>
            <th style={styles.th}>Qty</th>
            <th style={styles.th}>Unit Price</th>
            <th style={{ ...styles.th, textAlign: 'right' }}>Total</th>
          </tr>
        </thead>
        <tbody>
          {invoice.items.map((item, index) => (
            <tr key={index} style={styles.tableRow}>
              <td style={{ ...styles.td, textAlign: 'left' }}>{item.name}</td>
              <td style={styles.td}>{item.quantity}</td>
              <td style={styles.td}>${item.unitPrice.toFixed(2)}</td>
              <td style={{ ...styles.td, textAlign: 'right', fontWeight: '600' }}>
                ${item.total.toFixed(2)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Totals */}
      <div style={styles.totalsSection}>
        <div style={styles.totalsBox}>
          <div style={styles.totalRow}>
            <span style={styles.totalLabel}>Subtotal</span>
            <span style={styles.totalValue}>
              ${invoice.subtotal.toFixed(2)}
            </span>
          </div>
          <div style={styles.totalRow}>
            <span style={styles.totalLabel}>Tax ({invoice.tax}%)</span>
            <span style={styles.totalValue}>
              ${(invoice.subtotal * invoice.tax / 100).toFixed(2)}
            </span>
          </div>
          <div style={styles.grandTotalRow}>
            <span style={styles.grandTotalLabel}>Total Due</span>
            <span style={styles.grandTotalValue}>
              ${invoice.total.toFixed(2)}
            </span>
          </div>
        </div>
      </div>

      {/* Notes */}
      {invoice.notes && (
        <div style={styles.notesSection}>
          <p style={styles.notesLabel}>Notes</p>
          <p style={styles.notesText}>{invoice.notes}</p>
        </div>
      )}

      {/* Footer */}
      <div style={styles.footer}>
        <p>Thank you for your business!</p>
        <p>Generated by SmartBill</p>
      </div>

    </div>
  );
});

InvoiceTemplate.displayName = 'InvoiceTemplate';
export default InvoiceTemplate;

const styles = {
  page: {
    width: '794px',
    minHeight: '1123px',
    padding: '60px',
    backgroundColor: '#ffffff',
    fontFamily: 'Arial, sans-serif',
    color: '#1f2937',
    boxSizing: 'border-box',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '24px',
  },
  companyName: {
    fontSize: '24px',
    fontWeight: '700',
    color: '#2563eb',
    margin: '0 0 4px',
  },
  companyEmail: {
    fontSize: '13px',
    color: '#6b7280',
    margin: 0,
  },
  invoiceInfo: {
    textAlign: 'right',
  },
  invoiceTitle: {
    fontSize: '28px',
    fontWeight: '700',
    color: '#111827',
    margin: '0 0 4px',
    letterSpacing: '2px',
  },
  invoiceNo: {
    fontSize: '14px',
    color: '#6b7280',
    margin: '0 0 8px',
  },
  statusBadge: {
    fontSize: '12px',
    fontWeight: '600',
    border: '1px solid',
    padding: '3px 10px',
    borderRadius: '20px',
  },
  divider: {
    border: 'none',
    borderTop: '2px solid #e5e7eb',
    margin: '0 0 24px',
  },
  metaRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '32px',
  },
  metaLabel: {
    fontSize: '11px',
    fontWeight: '600',
    color: '#9ca3af',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    margin: '0 0 4px',
  },
  metaValue: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#111827',
    margin: '0 0 8px',
  },
  metaSubValue: {
    fontSize: '13px',
    color: '#6b7280',
    margin: 0,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    marginBottom: '24px',
  },
  tableHead: {
    backgroundColor: '#f9fafb',
    borderTop: '1px solid #e5e7eb',
    borderBottom: '1px solid #e5e7eb',
  },
  th: {
    padding: '10px 12px',
    fontSize: '12px',
    fontWeight: '600',
    color: '#6b7280',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  tableRow: {
    borderBottom: '1px solid #f3f4f6',
  },
  td: {
    padding: '12px',
    fontSize: '14px',
    color: '#374151',
    textAlign: 'center',
  },
  totalsSection: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginBottom: '32px',
  },
  totalsBox: {
    width: '280px',
  },
  totalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '6px 0',
    fontSize: '14px',
    borderBottom: '1px solid #f3f4f6',
  },
  totalLabel: {
    color: '#6b7280',
  },
  totalValue: {
    color: '#111827',
    fontWeight: '500',
  },
  grandTotalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '10px 0 0',
    marginTop: '4px',
  },
  grandTotalLabel: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#111827',
  },
  grandTotalValue: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#2563eb',
  },
  notesSection: {
    backgroundColor: '#f9fafb',
    borderRadius: '8px',
    padding: '16px',
    marginBottom: '32px',
  },
  notesLabel: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#6b7280',
    textTransform: 'uppercase',
    margin: '0 0 6px',
  },
  notesText: {
    fontSize: '14px',
    color: '#374151',
    margin: 0,
    lineHeight: '1.6',
  },
  footer: {
    borderTop: '1px solid #e5e7eb',
    paddingTop: '16px',
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '12px',
    color: '#9ca3af',
  },
};